default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: weather
  password: <%= ENV['WEATHER_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: weather_development

test:
  <<: *default
  database: weather_test

production:
  <<: *default
  database: weather
